# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings

title:       "Jingqi Lu | Portfolio"
description: "MUSA Student | Mobility | Spatial Justice | Network Science | Agentic Modelling"
author:      "Jingqi Lu"

collections:
  projects:
    output: true
    permalink: /:collection/:title