#-------------------------------
# General Site Settings

logo: '/assets/img/musa-logo.png'

intro_title: Spatial Data & AI for Smarter Cities
intro_text: |
  Urban Spatial Researcher | MS Candidate at UPenn. Specialized in translating complex urban phenomena into actionable spatial insights. With a background from UCL in Social Data Science, I focus on agent-based modeling (ABM) and mobility analytics to understand how infrastructure and policy influence urban equity and flow. I bridge the gap between geographic theory and computational execution to solve "wicked" urban problems.

resume: '/assets/files/CV_Jingqi.pdf'
resume_link_title: Download CV

menu:
- {name: 'Projects', url: ' '}
- {name: 'Blog and Creation',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Contact Section

social_label: Connect
social:
- {icon: 'github',   link: 'https://github.com/lluluciano0505'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jingqi-lu-04a910266'}
- {icon: 'envelope', link: 'mailto:lluluciano0505@gmail.com'}

#-------------------------------
# SEO Section

seo:
  description: 'Jingqi Lu | MUSA Student at UPenn | Spatial Data, AI Agent Modelling, Mobility & Spatial Justice'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

google-analytics-ua: ''

#-------------------------------
# Disqus Section

disqus:
  comments: false
  disqus_shortname: ''